import { useMemo, useState } from 'react'
import { Activity, Archive, ArrowUpRight, BookOpen, ChevronDown, ChevronRight, CircleHelp, FileText, LayoutGrid, Link2, Menu, Plus, Search, Settings2, SlidersHorizontal, Users, X } from 'lucide-react'
import './App.css'

const phases = [
  ['Scoping & Data Recon', 'SC', 'coral'], ['WBGT / UTCI Engine', 'WE', 'yellow'], ['Dataset + ML Model', 'ML', 'blue'],
  ['Backend + PostGIS', 'BE', 'green'], ['Dashboard', 'DB', 'violet'], ['Alert API', 'AP', 'orange'], ['Integration & Pitch', 'IP', 'pink'],
]
const initialFindings = [
  { id: 1, phase: 'Scoping & Data Recon', author: 'Kunal Choudhary', initials: 'KC', title: 'IMD publishes hourly observations through the API', body: 'The current observations endpoint gives us temperature, relative humidity, wind speed and rainfall for 764 stations. This is enough to start the data reconnaissance pass.', tags: ['data source', 'IMD'], time: '18 min ago', color: 'coral' },
  { id: 2, phase: 'Scoping & Data Recon', author: 'Aarav Mehta', initials: 'AM', title: 'Heatwave declaration needs a spatial context', body: 'A city-level warning can miss peri-urban exposure. Keep the first map layer at district resolution, then expose a finer grid when the live station feed is stable.', tags: ['open question', 'mapping'], time: '2 hours ago', color: 'blue' },
  { id: 3, phase: 'WBGT / UTCI Engine', author: 'Riya Sharma', initials: 'RS', title: 'Use UTCI for public-facing severity language', body: 'WBGT is useful for occupational guidance, while UTCI maps better to thermal stress bands for a public dashboard. We should retain both in the engine output.', tags: ['decision', 'formula'], time: 'Yesterday', color: 'yellow' },
]
const initialTeam = [
  { name: 'Kunal Choudhary', role: 'Product + frontend', initials: 'KC', status: 'online', color: 'coral' }, { name: 'Aarav Mehta', role: 'Data + ML', initials: 'AM', status: 'online', color: 'blue' },
  { name: 'Riya Sharma', role: 'Climate science', initials: 'RS', status: 'away', color: 'yellow' }, { name: 'Dev Patel', role: 'Backend + deployment', initials: 'DP', status: 'offline', color: 'green' },
]

function App() {
  const [activeTab, setActiveTab] = useState('Scoping & Data Recon')
  const [findings, setFindings] = useState(initialFindings)
  const [team, setTeam] = useState(initialTeam)
  const [quickRef, setQuickRef] = useState(true)
  const [composer, setComposer] = useState(false)
  const [search, setSearch] = useState('')
  const [mobileNav, setMobileNav] = useState(false)
  const [form, setForm] = useState({ title: '', body: '', author: 'Kunal Choudhary', tags: '' })
  const selectedPhase = phases.find((phase) => phase[0] === activeTab)
  const visibleFindings = useMemo(() => findings.filter((finding) => finding.phase === activeTab && (!search || `${finding.title} ${finding.body} ${finding.tags.join(' ')}`.toLowerCase().includes(search.toLowerCase()))), [activeTab, findings, search])
  const selectTab = (tab) => { setActiveTab(tab); setSearch(''); setMobileNav(false) }
  const addFinding = (event) => {
    event.preventDefault()
    if (!form.title.trim() || !form.body.trim()) return
    const author = team.find((member) => member.name === form.author) || team[0]
    setFindings([{ id: Date.now(), phase: activeTab, author: author.name, initials: author.initials, title: form.title, body: form.body, tags: form.tags.split(',').map((tag) => tag.trim()).filter(Boolean), time: 'Just now', color: author.color }, ...findings])
    setForm({ title: '', body: '', author: 'Kunal Choudhary', tags: '' }); setComposer(false)
  }
  return <div className="app-shell">
    <header className="topbar"><button className="mobile-menu" onClick={() => setMobileNav(!mobileNav)} aria-label="Toggle navigation"><Menu size={20} /></button><div className="brand"><span className="brand-mark"><Activity size={17} /></span><span>Fieldnotes</span><span className="brand-slash">/</span><span className="brand-project">SIH26083</span></div><div className="top-actions"><span className="sync-status"><span className="status-dot" /> Synced 2m ago</span><button className="icon-button" aria-label="Help"><CircleHelp size={18} /></button><button className="icon-button" aria-label="Settings"><Settings2 size={18} /></button><span className="top-avatar">KC</span></div></header>
    <div className="workspace"><aside className={`sidebar ${mobileNav ? 'sidebar-open' : ''}`}><div className="sidebar-section-label">Workspace</div><button className={`nav-item ${activeTab === 'overview' ? 'active' : ''}`} onClick={() => selectTab('overview')}><LayoutGrid size={16} /> Overview</button><button className={`nav-item ${activeTab === 'Team & Roles' ? 'active' : ''}`} onClick={() => selectTab('Team & Roles')}><Users size={16} /> Team & Roles <span className="nav-count">{team.length}</span></button><div className="sidebar-section-label phase-heading">Project phases <span>7</span></div><nav className="phase-list">{phases.map(([label, short, color]) => <button key={label} className={`phase-item ${activeTab === label ? 'active' : ''}`} onClick={() => selectTab(label)}><span className={`phase-icon ${color}`}>{short}</span><span>{label}</span><span className="phase-count">{findings.filter((finding) => finding.phase === label).length || ''}</span></button>)}</nav><div className="sidebar-bottom"><button className="nav-item"><Archive size={16} /> Archived</button><div className="project-meter"><div><span>Project progress</span><strong>34%</strong></div><div className="meter-track"><span /></div><small>7 phases · 12 findings</small></div></div></aside>
      <main className="main-content">{activeTab === 'overview' ? <Overview findings={findings} selectTab={selectTab} /> : activeTab === 'Team & Roles' ? <TeamView team={team} setTeam={setTeam} /> : <><div className="content-header"><div><div className="eyebrow"><span className={`phase-mini ${selectedPhase[2]}`}>{selectedPhase[1]}</span> Project phase</div><h1>{activeTab}</h1><p className="subtitle">Shared findings, decisions, and links for this lane.</p></div><button className="primary-button" onClick={() => setComposer(true)}><Plus size={17} /> Add finding</button></div><div className="toolbar"><div className="search-box"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search findings..." /></div><button className="filter-button"><SlidersHorizontal size={15} /> Filter <ChevronDown size={14} /></button><span className="result-count">{visibleFindings.length} {visibleFindings.length === 1 ? 'finding' : 'findings'}</span></div><section className={`reference-card ${quickRef ? 'open' : ''}`}><button className="reference-toggle" onClick={() => setQuickRef(!quickRef)}><span className="reference-icon"><BookOpen size={16} /></span><span><strong>Quick reference</strong><small>Pin the thresholds, formulas, and decisions your team keeps reaching for.</small></span><ChevronRight className="reference-chevron" size={17} /></button>{quickRef && <div className="reference-body"><div><span className="reference-label">WBGT heat stress</span><code>0.7 × Tw + 0.2 × Tg + 0.1 × Ta</code></div><div><span className="reference-label">Current note</span><p>Reference data is a shared space for the team. Add your meteorological thresholds here.</p></div><button className="text-button">Edit reference <ArrowUpRight size={14} /></button></div>}</section><div className="findings-list">{visibleFindings.length ? visibleFindings.map((finding) => <FindingCard key={finding.id} finding={finding} />) : <div className="empty-state"><FileText size={28} /><h3>No findings match</h3><p>Try a different search or add the first note for this phase.</p></div>}</div></>}</main></div>
    {composer && <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setComposer(false)}><form className="composer" onSubmit={addFinding}><div className="composer-header"><div><span className="eyebrow">New finding</span><h2>Add to {activeTab}</h2></div><button type="button" className="icon-button" onClick={() => setComposer(false)} aria-label="Close"><X size={19} /></button></div><label>Title<input autoFocus value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="What did the team learn?" /></label><label>Notes / links<textarea value={form.body} onChange={(event) => setForm({ ...form, body: event.target.value })} placeholder="Add context, a decision, or a useful link..." rows="5" /></label><div className="form-grid"><label>Contributor<select value={form.author} onChange={(event) => setForm({ ...form, author: event.target.value })}>{team.map((member) => <option key={member.name}>{member.name}</option>)}</select></label><label>Tags<input value={form.tags} onChange={(event) => setForm({ ...form, tags: event.target.value })} placeholder="data, decision" /></label></div><div className="composer-footer"><button type="button" className="secondary-button" onClick={() => setComposer(false)}>Cancel</button><button className="primary-button" type="submit"><Plus size={16} /> Publish finding</button></div></form></div>}
  </div>
}
function FindingCard({ finding }) { return <article className="finding-card"><div className="finding-meta"><span className={`avatar ${finding.color}`}>{finding.initials}</span><span><strong>{finding.author}</strong><small>{finding.time}</small></span><button className="card-more" aria-label="More options">···</button></div><h2>{finding.title}</h2><p>{finding.body}</p><div className="card-footer"><div className="tags">{finding.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><button className="link-button"><Link2 size={14} /> Copy link</button></div></article> }
function Overview({ findings, selectTab }) { return <div className="overview"><div className="content-header"><div><div className="eyebrow"><span className="pulse-dot" /> Team workspace</div><h1>Good morning, Kunal</h1><p className="subtitle">Here is where the heatwave prototype stands today.</p></div><button className="secondary-button"><Archive size={16} /> Export log</button></div><div className="overview-grid"><div className="overview-feature"><div className="feature-top"><span className="feature-kicker">Active sprint</span><span>Sep 01 — Sep 14</span></div><h2>Make the warning engine legible</h2><p>Connect the climate model output to language a district officer can act on in under a minute.</p><div className="feature-progress"><span><strong>3</strong> of 8 sprint tasks complete</span><div className="meter-track"><span /></div></div></div><div className="stat-card"><span>All findings</span><strong>{findings.length}</strong><small>+4 this week</small></div><div className="stat-card"><span>Open questions</span><strong>06</strong><small className="muted">Across 4 phases</small></div></div><div className="section-heading"><h2>Continue in a phase</h2><span>Most recently active</span></div><div className="phase-overview-list">{phases.slice(0, 4).map(([label, short, color]) => <button key={label} onClick={() => selectTab(label)}><span className={`phase-icon ${color}`}>{short}</span><span><strong>{label}</strong><small>{findings.filter((finding) => finding.phase === label).length || 0} findings · updated today</small></span><ChevronRight size={17} /></button>)}</div></div> }
function TeamView({ team, setTeam }) { const [newMember, setNewMember] = useState({ name: '', role: '' }); const addMember = (event) => { event.preventDefault(); if (!newMember.name.trim()) return; setTeam([...team, { ...newMember, initials: newMember.name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase(), status: 'offline', color: 'violet' }]); setNewMember({ name: '', role: '' }) }; return <div className="team-view"><div className="content-header"><div><div className="eyebrow"><Users size={15} /> Workspace people</div><h1>Team & Roles</h1><p className="subtitle">Keep the lanes clear so findings always have an owner.</p></div><button className="primary-button" onClick={() => document.querySelector('.team-form input')?.focus()}><Plus size={17} /> Add teammate</button></div><section className="team-card"><div className="team-card-heading"><div><h2>Project crew</h2><p>{team.length} people sharing this log</p></div><span className="team-avatars">{team.slice(0, 4).map((member) => <span key={member.name} className={`avatar small ${member.color}`}>{member.initials}</span>)}</span></div><div className="team-list">{team.map((member) => <div className="team-row" key={member.name}><span className={`avatar ${member.color}`}>{member.initials}</span><div><strong>{member.name}</strong><small>{member.role}</small></div><span className={`presence ${member.status}`}><i /> {member.status}</span><button className="icon-button" aria-label={`Edit ${member.name}`}><Settings2 size={16} /></button></div>)}</div></section><form className="team-form" onSubmit={addMember}><div><span className="eyebrow">Quick add</span><h2>Bring someone in</h2></div><input value={newMember.name} onChange={(event) => setNewMember({ ...newMember, name: event.target.value })} placeholder="Teammate name" /><input value={newMember.role} onChange={(event) => setNewMember({ ...newMember, role: event.target.value })} placeholder="Role or lane" /><button className="secondary-button" type="submit"><Plus size={16} /> Add</button></form></div> }
export default App
